import { LEGAL } from '@/lib/legal/config';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: `Privacy Policy · ${LEGAL.productName}`,
  description: 'How we collect, use, and protect your data.',
};

export default function PrivacyPage() {
  return (
    <>
      <h1>Privacy Policy</h1>
      <p className="effective-line">Effective {LEGAL.effectiveDate}</p>

      <p>
        This policy explains what personal information {LEGAL.legalEntity} (&ldquo;we&rdquo;)
        collects when you use {LEGAL.productName}, why we collect it, how long we keep it, and
        what rights you have. If anything here is unclear, email us at
        {' '}<a href={`mailto:${LEGAL.privacyEmail}`}>{LEGAL.privacyEmail}</a>.
      </p>

      <div className="callout">
        <strong>Short version.</strong> We collect only what we need to run the Service:
        account info, the content you submit for review, and standard operational logs. We never
        sell your data. We never train foundation models on your content.
      </div>

      <h2 id="data-controller">1. Who is responsible for your data</h2>
      <p>
        The <strong>data controller</strong> for your personal information is:
      </p>
      <p>
        {LEGAL.legalEntity}<br />
        {LEGAL.legalAddress}<br />
        Contact: <a href={`mailto:${LEGAL.privacyEmail}`}>{LEGAL.privacyEmail}</a>
      </p>

      <h2 id="collected">2. What we collect</h2>
      <h3>Account data</h3>
      <ul>
        <li>Email address (required)</li>
        <li>Display name (optional)</li>
        <li>Password hash (we never store plaintext passwords)</li>
        <li>Workspace and team-membership metadata</li>
      </ul>

      <h3>Content you submit</h3>
      <ul>
        <li>Scripts, titles, descriptions, thumbnails, uploaded video files</li>
        <li>Analysis results and reports generated by the Service</li>
      </ul>

      <h3>Billing data</h3>
      <p>
        Billing is handled by our Merchant of Record, <strong>{LEGAL.merchantOfRecord}</strong>.
        We receive a subscription status, plan tier, and invoice history from Lemon Squeezy — we
        never see or store your full payment card number. Lemon Squeezy&rsquo;s privacy notice is at
        {' '}<a href="https://www.lemonsqueezy.com/privacy" target="_blank" rel="noopener noreferrer">
        lemonsqueezy.com/privacy</a>.
      </p>

      <h3>Operational data</h3>
      <ul>
        <li>IP address (used for rate limiting and abuse prevention)</li>
        <li>Browser and OS user-agent</li>
        <li>Timestamps of requests</li>
        <li>Aggregate feature-usage counts (which pages, how often)</li>
      </ul>

      <h3>What we do NOT collect</h3>
      <ul>
        <li>We do not collect biometric data.</li>
        <li>We do not use third-party ad-tracking pixels.</li>
        <li>We do not read your emails, DMs, or accounts on other platforms.</li>
        <li>We do not sell personal information to anyone, ever.</li>
      </ul>

      <h2 id="why">3. Why we process your data (legal bases)</h2>
      <p>Under GDPR, we process personal data on these legal bases:</p>
      <ul>
        <li><strong>Contract</strong> — to provide the Service you signed up for.</li>
        <li><strong>Legitimate interest</strong> — to secure the Service, prevent abuse, and improve quality.</li>
        <li><strong>Legal obligation</strong> — to comply with tax, accounting, and law-enforcement requests.</li>
        <li><strong>Consent</strong> — where required (e.g. non-essential cookies, marketing emails).</li>
      </ul>

      <h2 id="ai">4. AI processing of your content</h2>
      <p>
        To produce a review, we send your submitted content to <strong>NVIDIA NIM</strong>
        (our large-language and vision-model provider) over an encrypted connection. NVIDIA
        processes the content transiently to generate the review response and does not retain
        it for model training. See
        {' '}<a href="https://www.nvidia.com/en-us/about-nvidia/privacy-policy/" target="_blank" rel="noopener noreferrer">
          NVIDIA&rsquo;s privacy policy</a>.
      </p>
      <p>
        We <strong>do not</strong> use your content to train our own models, or any third party&rsquo;s
        models, without your explicit prior consent.
      </p>

      <h2 id="sub-processors">5. Sub-processors we use</h2>
      <p>We rely on these vendors to run the Service. Each is bound by data-processing agreements.</p>
      <ul>
        <li><strong>{LEGAL.merchantOfRecord}</strong> — payments, tax, invoicing</li>
        <li><strong>NVIDIA (NIM API)</strong> — LLM and vision-model inference</li>
        <li><strong>Vercel / hosting provider</strong> — application hosting and edge CDN</li>
        <li><strong>Neon or Supabase</strong> — application database</li>
        <li><strong>UploadThing or Cloudflare R2</strong> — file storage for uploaded video assets</li>
        <li><strong>Resend</strong> — transactional email delivery</li>
        <li><strong>PostHog</strong> — anonymized product analytics (opt-out available)</li>
        <li><strong>Sentry</strong> — error monitoring</li>
      </ul>
      <p>
        A current list is maintained at <a href="/legal/subprocessors">/legal/subprocessors</a> and will be
        updated whenever it changes.
      </p>

      <h2 id="retention">6. How long we keep your data</h2>
      <ul>
        <li><strong>Account and profile</strong>: while your account is active, plus 30 days after cancellation to allow re-activation.</li>
        <li><strong>Submitted content and reports</strong>: while your account is active. On deletion, purged within 30 days.</li>
        <li><strong>Invoices</strong>: retained for 7 years to satisfy tax and accounting law.</li>
        <li><strong>Support conversations</strong>: 24 months.</li>
        <li><strong>Server logs</strong>: 90 days.</li>
      </ul>

      <h2 id="rights">7. Your rights</h2>
      <p>Regardless of where you live, you have the right to:</p>
      <ul>
        <li><strong>Access</strong> — request a copy of your personal data.</li>
        <li><strong>Correct</strong> — fix inaccurate or incomplete data.</li>
        <li><strong>Delete</strong> — have us erase your account and content (see below).</li>
        <li><strong>Export</strong> — receive your data in a portable format.</li>
        <li><strong>Object</strong> — opt out of processing that relies on legitimate interest.</li>
        <li><strong>Withdraw consent</strong> — where processing is based on consent.</li>
      </ul>
      <p>
        Exercise any of these rights from Settings &rsaquo; Data, or by emailing
        {' '}<a href={`mailto:${LEGAL.privacyEmail}`}>{LEGAL.privacyEmail}</a>. We respond within 30 days.
      </p>

      <h2 id="ccpa">8. California residents (CCPA/CPRA)</h2>
      <p>
        California residents have the additional rights to (a) know what personal information we
        collect and disclose about them, (b) delete that information, (c) correct inaccuracies,
        (d) opt out of &ldquo;sale&rdquo; or &ldquo;sharing&rdquo; of their personal information,
        and (e) not be discriminated against for exercising these rights. We do not sell personal
        information as defined by CCPA/CPRA.
      </p>

      <h2 id="transfers">9. International transfers</h2>
      <p>
        Your data may be processed in countries outside your own, including the United States.
        Where we transfer data out of the European Economic Area or United Kingdom, we rely on
        Standard Contractual Clauses or an equivalent legal mechanism to protect your rights.
      </p>

      <h2 id="security">10. Security</h2>
      <p>
        We use TLS 1.2+ for all data in transit and encryption at rest for stored data. Passwords
        are hashed with a modern KDF. Access to production systems is limited and logged. Despite
        these measures, no system is 100% secure — if we discover a breach affecting your data,
        we will notify you and the relevant authorities as required by law.
      </p>

      <h2 id="cookies">11. Cookies</h2>
      <p>
        See our separate <a href="/legal/cookies">Cookie Policy</a> for what we use, why, and how
        to change your preferences.
      </p>

      <h2 id="children">12. Children</h2>
      <p>
        The Service is not directed to children under 16. We do not knowingly collect personal
        data from children under 16. If you believe we have, contact
        {' '}<a href={`mailto:${LEGAL.privacyEmail}`}>{LEGAL.privacyEmail}</a> and we will delete it.
      </p>

      <h2 id="changes">13. Changes to this policy</h2>
      <p>
        We&rsquo;ll notify you in-app and by email at least 14 days before any material change
        takes effect. Non-material changes take effect on publication.
      </p>

      <h2 id="complaints">14. Complaints</h2>
      <p>
        If you are in the EU/EEA/UK and believe we have not handled your data lawfully, you may
        lodge a complaint with your local data-protection authority. We&rsquo;d appreciate the
        chance to address your concern first — reach us at
        {' '}<a href={`mailto:${LEGAL.privacyEmail}`}>{LEGAL.privacyEmail}</a>.
      </p>
    </>
  );
}
