-- AlterColumn
ALTER TABLE "Channel" ALTER COLUMN "subscribers" SET DATA TYPE BIGINT;
ALTER TABLE "Channel" ALTER COLUMN "videosCount" SET DATA TYPE BIGINT;
ALTER TABLE "Channel" ALTER COLUMN "viewsCount" SET DATA TYPE BIGINT;
