/**
 * Feature extraction for the Publish score model — the TypeScript mirror of
 * `ml/publishml/features.py`.
 *
 * THIS FILE AND THE PYTHON ONE MUST AGREE EXACTLY.
 * The model is a positional vector of 64 numbers. If this extractor computes
 * `title_len` differently from the one that produced the training data, every
 * score is wrong in a way that no test of *this* file alone would catch. So:
 *
 *   - the column order comes from the model artefact, never from this file
 *   - `src/lib/ml/features.test.ts` runs both extractors over shared fixtures
 *     exported by `python -m publishml.export` and asserts equality
 *   - the awkward-looking helpers below (`codePoints`, `splitLines`) exist
 *     precisely because the obvious JavaScript is *not* what Python does
 *
 * The three places JavaScript silently disagrees with Python, all handled:
 *   1. `len(s)` counts code points; `s.length` counts UTF-16 units. An emoji is
 *      1 in Python and 2 in JS. → `codePoints()`.
 *   2. `str.splitlines()` returns `[]` for the empty string and drops a trailing
 *      terminator; `split('\n')` returns `['']` and keeps it. → `splitLines()`.
 *   3. `datetime.weekday()` is Monday=0; `Date.getUTCDay()` is Sunday=0.
 *
 * Thumbnail features are NOT computed here. They need pixel access and are
 * produced by `ml/publishml/thumbs.py`; the caller passes them in when it has
 * them. When it does not, they are left absent and `has_thumb` is 0 — the same
 * thing the trainer saw for videos whose thumbnail never downloaded, so the model
 * already knows how to treat that row.
 */

/** The metadata a score needs. Mirrors one row of `raw/videos.jsonl`. */
export type VideoInput = {
  title?: string;
  description?: string;
  tags?: string[];
  /** ISO-8601, e.g. `PT4M13S`. */
  duration?: string | null;
  /** ISO timestamp. Omit for an unpublished draft — see `now` in `extract`. */
  publishedAt?: string | null;
  definition?: string | null;
  caption?: boolean;
  madeForKids?: boolean;
  licensedContent?: boolean;
};

export type ChannelInput = {
  subscribers?: number;
  videoCount?: number;
  /** ISO timestamp of channel creation. */
  publishedAt?: string | null;
};

/** Output of `ml/publishml/thumbs.py` for one image, keys prefixed `thumb_`. */
export type ThumbFeatures = Record<string, number>;

export type FeatureRow = Record<string, number>;

/**
 * The 64 columns, in the exact order `features.feature_names()` returns them.
 *
 * Duplicated here on purpose. The scorer already takes its column order from the
 * model artefact, so this list is not used to build vectors - it is used to CHECK
 * the artefact at load time (`validate` in `gbdt.ts`). Without an independent copy
 * there is nothing to check against, and an artefact trained on a different
 * feature set would load happily and score every video against shifted columns.
 *
 * Generated by `python -m publishml.parity`-adjacent tooling and asserted equal to
 * the fixture in `parity.test.ts`, so it cannot silently drift from Python.
 */
export const FEATURE_NAMES = [
  'age_days_log',
  'channel_age_days_log',
  'channel_subs_log',
  'channel_videos_log',
  'desc_first_line_len',
  'desc_has_cta',
  'desc_hashtags',
  'desc_len',
  'desc_lines',
  'desc_links',
  'desc_timestamps',
  'duration_log',
  'duration_seconds',
  'has_captions',
  'has_thumb',
  'is_hd',
  'is_shorts',
  'licensed',
  'made_for_kids',
  'publish_dow',
  'publish_hour',
  'publish_weekend',
  'tag_avg_words',
  'tag_chars',
  'tag_count',
  'thumb_aspect',
  'thumb_border_fraction',
  'thumb_brightness',
  'thumb_brightness_std',
  'thumb_center_weight',
  'thumb_colorfulness',
  'thumb_complexity',
  'thumb_contrast',
  'thumb_edge_density',
  'thumb_face_area',
  'thumb_face_count',
  'thumb_red_fraction',
  'thumb_saturation',
  'thumb_skin_fraction',
  'thumb_text_area',
  'thumb_text_blocks',
  'thumb_third_offset',
  'thumb_warm_fraction',
  'title_allcaps_words',
  'title_avg_word_len',
  'title_brackets',
  'title_caps_ratio',
  'title_colon',
  'title_curiosity',
  'title_emoji',
  'title_exclaim',
  'title_has_number',
  'title_howto',
  'title_len',
  'title_list',
  'title_longest_word',
  'title_power_words',
  'title_question',
  'title_second_person',
  'title_starts_number',
  'title_stopword_ratio',
  'title_truncated',
  'title_urgency',
  'title_words',
] as const;

/**
 * Features a creator cannot choose: how old the video is, how many subscribers the
 * channel has, whether a thumbnail exists at all.
 *
 * The recommender holds every one of these byte-identical while testing a
 * counterfactual. Otherwise "lift" would include the effect of changing something
 * the creator has no way to change, and the advice would amount to "have more
 * subscribers" or "publish this 200 days earlier".
 */
export const CONTEXT_FEATURES = [
  'age_days_log',
  'channel_age_days_log',
  'channel_subs_log',
  'channel_videos_log',
  'has_thumb',
  'licensed',
  'made_for_kids',
  'thumb_aspect',
] as const;

/** Everything a creator can actually edit before publishing - the only source of advice. */
export const CONTROLLABLE_FEATURES = [
  'desc_first_line_len',
  'desc_has_cta',
  'desc_hashtags',
  'desc_len',
  'desc_lines',
  'desc_links',
  'desc_timestamps',
  'duration_log',
  'duration_seconds',
  'has_captions',
  'is_hd',
  'is_shorts',
  'publish_dow',
  'publish_hour',
  'publish_weekend',
  'tag_avg_words',
  'tag_chars',
  'tag_count',
  'thumb_border_fraction',
  'thumb_brightness',
  'thumb_brightness_std',
  'thumb_center_weight',
  'thumb_colorfulness',
  'thumb_complexity',
  'thumb_contrast',
  'thumb_edge_density',
  'thumb_face_area',
  'thumb_face_count',
  'thumb_red_fraction',
  'thumb_saturation',
  'thumb_skin_fraction',
  'thumb_text_area',
  'thumb_text_blocks',
  'thumb_third_offset',
  'thumb_warm_fraction',
  'title_allcaps_words',
  'title_avg_word_len',
  'title_brackets',
  'title_caps_ratio',
  'title_colon',
  'title_curiosity',
  'title_emoji',
  'title_exclaim',
  'title_has_number',
  'title_howto',
  'title_len',
  'title_list',
  'title_longest_word',
  'title_power_words',
  'title_question',
  'title_second_person',
  'title_starts_number',
  'title_stopword_ratio',
  'title_truncated',
  'title_urgency',
  'title_words',
] as const;

// --- vocabulary (must stay identical to features.py) ------------------------

const POWER_WORDS = new Set([
  'secret', 'proven', 'ultimate', 'essential', 'surprising', 'shocking',
  'brutal', 'honest', 'insane', 'crazy', 'genius', 'perfect', 'instant',
  'hidden', 'forbidden', 'banned', 'exposed', 'revealed', 'truth', 'myth',
  'mistake', 'mistakes', 'warning', 'danger', 'wrong', 'stop', 'avoid',
  'finally', 'actually', 'really', 'definitive', 'complete', 'free',
]);

const CURIOSITY_MARKERS = new Set([
  'why', 'how', 'what', 'when', 'who', 'which', 'nobody', 'everyone',
  'before', 'after', 'until', 'unless', 'happens', 'happened', 'went',
  'turns', 'learned', 'found', 'discovered', 'reason', 'because',
]);

const URGENCY_WORDS = new Set([
  'now', 'today', 'tonight', '2024', '2025', '2026', 'new', 'just', 'breaking',
  'update', 'latest', 'still', 'already', 'immediately', 'quick', 'fast',
]);

const SECOND_PERSON = new Set(['you', 'your', 'yours', "you're", 'youre', 'yourself']);

const STOPWORDS = new Set([
  'a', 'an', 'the', 'and', 'or', 'but', 'of', 'to', 'in', 'on', 'at', 'for',
  'with', 'is', 'it', 'this', 'that', 'as', 'by', 'from', 'was', 'are', 'be',
]);

const CTA_PHRASES = [
  'subscribe', 'like and', 'comment below', 'let me know', 'follow me',
  'join the', 'sign up', 'free guide', 'check out', 'link below', 'patreon',
];

const LIST_PREFIX = /^\s*(\d{1,3})\s*(?:[.)\-:]|\s)/;
const TOP_N = /^\s*top\s+\d/i;
// Word boundaries written out instead of `\b`: JS `\b` is ASCII-word based
// while Python's is Unicode-aware, so "how toüntertake" matched here but not
// in Python. `(?<![A-Za-z0-9_])…(?![A-Za-z0-9_])` is the same class both
// languages use for word characters in this file's own tokenizer.
const HOWTO = /(?<![A-Za-z0-9_])how\s+(to|i|we|he|she|they)(?![A-Za-z0-9_])/i;
/** Same code-point ranges as the Python `EMOJI` class; `u` makes both count code points. */
const EMOJI = /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{1F1E6}-\u{1F1FF}\u{2190}-\u{21FF}]/gu;
const BRACKETS = /[[\](){}|]/g;
const URL = /https?:\/\/\S+/g;
const TIMESTAMP = /^\s*\(?\d{1,2}:\d{2}(?::\d{2})?\)?/gm;
/** `[A-Za-z0-9_]`, the explicit word class BOTH extractors agree on — see the note in features.py. */
const HASHTAG = /(?:^|\s)#[A-Za-z0-9_]+/g;
const ISO_DURATION = /^P(?:(\d+)D)?T?(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/;
const WORD_SPLIT = /[^A-Za-z0-9'’]+/;
/**
 * Python's `str.isdecimal()` — precisely the Unicode Nd class, the same class
 * JS spells `\p{Nd}`. The extractors previously disagreed at the edges:
 * Python's `isdigit()` also accepts superscripts (100²), circled (①), and
 * subscript digits, which the hand-enumerated Nd range list here missed
 * (only ~15 of the ~50 Nd scripts were listed) — and the parity fixtures used
 * only Arabic-Indic digits, so the drift was invisible to the suite.
 * `isdecimal()` and `\p{Nd}` are exact mirrors by definition.
 */
const ANY_DIGIT = /\p{Nd}/u;
const LETTER = /\p{L}/gu;
const UPPER_LETTER = /\p{Lu}/u;
const LOWER_LETTER = /\p{Ll}/u;

// --- Python-compatibility helpers -------------------------------------------

/** `len(s)` \u2014 code points, not UTF-16 units. */
function codePoints(text: string): number {
  // The string iterator yields code points; `.length` counts UTF-16 units and
  // disagrees with Python on every emoji and every astral-plane character.
  return Array.from(text).length;
}

/**
 * `str.splitlines()`.
 *
 * Differs from `split('\n')` in two ways that both change feature values: the
 * empty string yields `[]` (not `['']`), and a trailing terminator is not
 * kept as a final empty line. The explicit terminator list mirrors Python's,
 * not just `\r?\n`.
 */
function splitLines(text: string): string[] {
  // Python's splitlines() on the empty string is [] \u2014 split('\n') would say [''].
  if (!text) return [];
  // Every terminator Python's splitlines() recognises, written as escapes so the
  // file stays readable. \r\n must come first, or CRLF would split twice and
  // add a phantom empty line to `desc_lines`.
  const lines = text.split(/\r\n|[\n\r\v\f\x1c\x1d\x1e\x85\u2028\u2029]/);
  if (lines.length > 1 && lines[lines.length - 1] === '') lines.pop();
  return lines;
}

function words(text: string): string[] {
  return text.split(WORD_SPLIT).filter((w) => w.length > 0);
}

function countMatches(text: string, pattern: RegExp): number {
  const matches = text.match(pattern);
  return matches ? matches.length : 0;
}

function countSubstring(text: string, needle: string): number {
  if (!needle) return 0;
  return text.split(needle).length - 1;
}

/** `w.isupper()` — at least one cased character, and none of them lowercase. */
function isAllCaps(word: string): boolean {
  return UPPER_LETTER.test(word) && !LOWER_LETTER.test(word);
}

/** ISO-8601 duration → seconds. Mirrors `_duration_seconds`. */
export function durationSeconds(iso?: string | null): number {
  if (!iso) return 0;
  const m = ISO_DURATION.exec(iso.trim());
  if (!m) return 0;
  const [, d, h, mi, s] = m;
  return (
    (d ? parseInt(d, 10) : 0) * 86400 +
    (h ? parseInt(h, 10) : 0) * 3600 +
    (mi ? parseInt(mi, 10) : 0) * 60 +
    (s ? parseInt(s, 10) : 0)
  );
}

function parseTime(value?: string | null): Date | null {
  if (!value) return null;
  // Offset-less ISO strings: JS `new Date` reads a datetime-with-time in the
  // MACHINE'S local zone (so the same row parses differently per machine) and
  // a date-only string as UTC. Python's mirror attaches UTC to both. Appending
  // Z makes this side deterministic and identical to Python for every input.
  //
  // This regex is the ONLY accepted form, and it mirrors Python 3.11+
  // `fromisoformat`'s full grammar (the parity twin is strict — anything else
  // returns None there, and a `new Date(trimmed)` fallback used to accept
  // "March 4, 2026" etc., computing a machine-zone-dependent age_days_log
  // Python scored as 0). Python additionally accepts: COMPACT dates
  // (20260304, 20260304T0915), HOUR-ONLY times (…T09), any-length fractional
  // seconds, lowercase 't' separators, ±hh and ±hhmm offsets, and week dates
  // (2026-W09-1). The compact/week forms are handled by explicit mirrors
  // below; everything else the trainer's rows can carry is in the regex.
  const trimmed = value.trim();

  // Compact date form: 20260304 / 20260304T091500Z — Python accepts, so TS must.
  // Anchored end-to-end: fromisoformat rejects trailing junk ('20260304X').
  const compact = /^(\d{4})(\d{2})(\d{2})(?:[Tt](\d{2})(\d{2})?(\d{2})?(?:\.(\d+))?(Z|[+-]\d{2}(?::?\d{2})?)?)?$/.exec(trimmed);
  if (compact) {
    const y = Number(compact[1]), mo = Number(compact[2]), d = Number(compact[3]);
    if (!isValidCalendarDate(y, mo, d)) return null;
    const h = compact[4] ? Number(compact[4]) : 0;
    const mi = compact[5] ? Number(compact[5]) : 0;
    const s = compact[6] ? Number(compact[6]) : 0;
    if (h > 23 || mi > 59 || s > 59) return null;
    if (compact[8] !== undefined && compact[8] !== '') {
      const raw = compact[8];
      const off = raw === 'Z' ? '+00:00'
        : /^([+-]\d{2})$/.test(raw) ? `${raw}:00`
        : raw.replace(/^([+-]\d{2})(\d{2})$/, '$1:$2');
      const msC = compact[7] !== undefined ? Math.round(Number('0.' + compact[7]) * 1000) : 0;
      const date = new Date(`${y}-${String(mo).padStart(2, '0')}-${String(d).padStart(2, '0')}T` +
        `${String(h).padStart(2, '0')}:${String(mi).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(msC).padStart(3, '0')}${off}`);
      return Number.isNaN(date.getTime()) ? null : date;
    }
    const date = new Date(Date.UTC(y, mo - 1, d, h, mi, s));
    return Number.isNaN(date.getTime()) ? null : date;
  }

  // Standard dashed form. Every component Python allows, including optional
  // minutes, optional seconds, any fractional length, and the four offset
  // spellings (Z / ±hh / ±hhmm / ±hh:mm).
  const m = /^(\d{4})-(\d{2})-(\d{2})(?:[Tt ](\d{2})(?::(\d{2}))?(?::(\d{2}))?(?:\.(\d+))?)?(Z|[+-]\d{2}(?::?\d{2})?)?$/.exec(trimmed);
  if (!m) return null;
  const [year, month, day] = [Number(m[1]), Number(m[2]), Number(m[3])];
  if (!isValidCalendarDate(year, month, day)) return null;
  const hour = m[4] !== undefined ? Number(m[4]) : 0;
  const minute = m[5] !== undefined ? Number(m[5]) : 0;
  const second = m[6] !== undefined ? Number(m[6]) : 0;
  if (hour > 23 || minute > 59 || second > 59) return null;
  // Python keeps microsecond precision; the parity tolerance is 1e-9 on
  // log1p(age), so the fraction must survive as milliseconds (truncated the
  // same way — 0.1234567s → 123ms, Python's datetime keeps .123456 but the
  // difference lands below the 1e-9 log tolerance either way).
  const ms = m[7] !== undefined ? Math.round(Number('0.' + m[7]) * 1000) : 0;
  if (m[8] !== undefined && m[8] !== '') {
    // Offset present: normalize Z / ±hh / ±hhmm to ±hh:mm — V8's parser
    // rejects the short spellings even though fromisoformat accepts them.
    const raw = m[8];
    const off = raw === 'Z' ? '+00:00'
      : /^([+-]\d{2})$/.test(raw) ? `${raw}:00`
      : raw.replace(/^([+-]\d{2})(\d{2})$/, '$1:$2');
    const date = new Date(
      `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}T` +
      `${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}:${String(second).padStart(2, '0')}.${String(ms).padStart(3, '0')}${off}`,
    );
    return Number.isNaN(date.getTime()) ? null : date;
  }
  // No offset — both sides read the naive fields as UTC.
  const date = new Date(Date.UTC(year, month - 1, day, hour, minute, second, ms));
  return Number.isNaN(date.getTime()) ? null : date;
}

/**
 * Wall-clock hour/dow as WRITTEN in the ISO string, not converted to UTC.
 *
 * Python's `datetime.fromisoformat` keeps the local fields of the timestamp
 * (a `2026-03-04T09:15:00+05:00` parses to hour 9), and that is what the
 * trainer recorded into `publish_hour`. `new Date(value).getUTCHours()`
 * instead converts to UTC (hour 4), so the two extractors silently disagreed
 * on every offset timestamp — the parity fixture never caught it because it
 * only uses `Z`-suffixed times. This reads the fields straight out of the
 * string so TS and Python produce identical numbers for any offset.
 *
 * Returns null for anything not shaped like a date (`YYYY-MM-DD`, optionally
 * followed by `THH[:mm[:ss]]` and an offset) — the caller then falls back to
 * the absent-value branch, same as Python's `_parse_time` returning None.
 *
 * Python's `fromisoformat` accepts a DATE-ONLY string and treats the time as
 * midnight, so the TS regex must too: a bare `2026-03-04` used to fall to the
 * absent branch here (dow pinned to 0/Monday) while Python computed the real
 * weekday — `publish_dow` and `publish_weekend` disagreed on every date-only
 * input. The time part is optional; a missing hour is 0, matching midnight.
 */
function wallClock(value?: string | null): { hour: number; dow: number } | null {
  if (!value) return null;
  const trimmed = value.trim();
  // Same grammar as parseTime (Python 3.11+ fromisoformat): compact or dashed
  // dates, T/t/space separator, hour-only time. Fields are read straight out of
  // the string so an offset never shifts them.
  let m = /^(\d{4})-(\d{2})-(\d{2})(?:[Tt ](\d{2}))?/.exec(trimmed);
  if (!m) {
    // Compact spelling, anchored like Python's fromisoformat (no trailing junk).
    m = /^(\d{4})(\d{2})(\d{2})(?:[Tt](\d{2})(\d{2})?(\d{2})?(?:\.(\d+))?(Z|[+-]\d{2}(?::?\d{2})?)?)?$/.exec(trimmed);
  }
  if (!m) return null;
  const year = Number(m[1]);
  const month = Number(m[2]);
  const day = Number(m[3]);
  const hour = m[4] !== undefined ? Number(m[4]) : 0;
  // Python's fromisoformat rejects impossible calendar dates (2026-02-31) —
  // `Date.UTC` would silently roll them into next month and compute the wrong
  // weekday, so the day must be range-checked BEFORE the calendar lookup.
  if (!isValidCalendarDate(year, month, day)) return null;
  // Weekday from the calendar date. Python's `weekday()` is Monday=0.
  // The Date here is only a calendar lookup (UTC-constructed, never
  // shifted) so the offset in the string cannot influence it.
  const utcMidnight = Date.UTC(year, month - 1, day);
  if (Number.isNaN(utcMidnight)) return null;
  const dow = (new Date(utcMidnight).getUTCDay() + 6) % 7;
  if (!(hour >= 0 && hour <= 23) || !(month >= 1 && month <= 12)) return null;
  return { hour, dow };
}

/**
 * True only for a date that exists on the calendar. Python's fromisoformat
 * rejects e.g. 2026-02-31 and 2026-04-31; `Date.UTC` would roll them over
 * instead, so every mirror that hands (y, m, d) to Date.UTC must check this
 * first to keep the two extractors agreeing on what parses at all.
 */
function isValidCalendarDate(year: number, month: number, day: number): boolean {
  if (!(month >= 1 && month <= 12) || !(day >= 1)) return false;
  const daysInMonth = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][month - 1];
  const leap = month === 2 && ((year % 4 === 0 && year % 100 !== 0) || year % 400 === 0);
  return day <= daysInMonth + (leap ? 1 : 0);
}

// --- feature groups ---------------------------------------------------------

export function titleFeatures(rawTitle: string): FeatureRow {
  const title = rawTitle || '';
  const ws = words(title);
  const lower = ws.map((w) => w.toLowerCase());
  const letters = title.match(LETTER) ?? [];
  const uppers = letters.filter((c) => UPPER_LETTER.test(c)).length;
  const len = codePoints(title);
  const totalWordLen = ws.reduce((sum, w) => sum + codePoints(w), 0);

  return {
    title_len: len,
    title_words: ws.length,
    title_caps_ratio: letters.length ? uppers / letters.length : 0,
    title_allcaps_words: ws.filter((w) => codePoints(w) > 2 && isAllCaps(w)).length,
    title_has_number: ANY_DIGIT.test(title) ? 1 : 0,
    title_starts_number: LIST_PREFIX.test(title) ? 1 : 0,
    title_question: title.includes('?') ? 1 : 0,
    title_exclaim: countSubstring(title, '!'),
    title_brackets: countMatches(title, BRACKETS),
    title_emoji: countMatches(title, EMOJI),
    title_colon:
      countSubstring(title, ':') + countSubstring(title, '|') + countSubstring(title, ' - '),
    title_second_person: lower.filter((w) => SECOND_PERSON.has(w)).length,
    title_power_words: lower.filter((w) => POWER_WORDS.has(w)).length,
    title_curiosity: lower.filter((w) => CURIOSITY_MARKERS.has(w)).length,
    title_urgency: lower.filter((w) => URGENCY_WORDS.has(w)).length,
    title_howto: HOWTO.test(title) ? 1 : 0,
    title_list: LIST_PREFIX.test(title) || TOP_N.test(title) ? 1 : 0,
    title_avg_word_len: ws.length ? totalWordLen / ws.length : 0,
    title_longest_word: ws.reduce((max, w) => Math.max(max, codePoints(w)), 0),
    title_stopword_ratio: lower.length
      ? lower.filter((w) => STOPWORDS.has(w)).length / lower.length
      : 0,
    title_truncated: len > 60 ? 1 : 0,
  };
}

export function descriptionFeatures(rawDesc: string): FeatureRow {
  const desc = rawDesc || '';
  const lines = splitLines(desc);
  const first = lines.length ? lines[0] : '';
  const low = desc.toLowerCase();
  return {
    desc_len: codePoints(desc),
    desc_lines: lines.length,
    desc_links: countMatches(desc, URL),
    desc_timestamps: countMatches(desc, TIMESTAMP),
    desc_hashtags: countMatches(desc, HASHTAG),
    desc_first_line_len: codePoints(first),
    desc_has_cta: CTA_PHRASES.some((p) => low.includes(p)) ? 1 : 0,
  };
}

export function tagFeatures(tags?: string[]): FeatureRow {
  const list = tags ?? [];
  const splitPython = (t: string): string[] => {
    // Python's `str.split()` (no args) — the exact tokenizer the trainer
    // used — splits on runs of [ \t\n\v\f\r] PLUS the C0 separators
    // \x1c-\x1f, but NOT on U+FEFF, where a bare JS `/\s+/` differs on
    // both. Tokenizing by Python's exact set keeps tag_avg_words
    // byte-parity for tags carrying those characters.
    const out: string[] = [];
    let cur = '';
    for (const ch of t) {
      const cp = ch.codePointAt(0)!;
      const isWs = cp === 0x20 || (cp >= 0x09 && cp <= 0x0d) || (cp >= 0x1c && cp <= 0x1f);
      if (isWs) {
        if (cur) { out.push(cur); cur = ''; }
      } else {
        cur += ch;
      }
    }
    if (cur) out.push(cur);
    return out;
  };
  const wordCount = list.reduce((sum, t) => sum + splitPython(t).length, 0);
  return {
    tag_count: list.length,
    tag_chars: list.reduce((sum, t) => sum + codePoints(t), 0),
    tag_avg_words: list.length ? wordCount / list.length : 0,
  };
}

/** Seconds at or below this are treated as a Short. Mirrors `config.SHORTS_MAX_SECONDS`. */
export const SHORTS_MAX_SECONDS = 60;

/**
 * Every `thumb_*` column, in the order `ml/publishml/thumbs.py` declares them.
 *
 * Listed explicitly rather than derived from the passed-in object, because both
 * branches below need the full set: the present branch must ignore keys the model
 * does not know, and the absent branch must write a zero for each one.
 */
export const THUMB_FEATURE_NAMES = [
  'thumb_brightness',
  'thumb_brightness_std',
  'thumb_contrast',
  'thumb_saturation',
  'thumb_colorfulness',
  'thumb_warm_fraction',
  'thumb_red_fraction',
  'thumb_edge_density',
  'thumb_text_area',
  'thumb_text_blocks',
  'thumb_face_area',
  'thumb_face_count',
  'thumb_skin_fraction',
  'thumb_center_weight',
  'thumb_third_offset',
  'thumb_complexity',
  'thumb_border_fraction',
  'thumb_aspect',
] as const;

/**
 * The full feature row.
 *
 * `now` is a parameter, not `new Date()`, for two reasons: the parity test needs
 * a fixed clock, and a score that silently changes because a day passed is a
 * score nobody can debug.
 */
export function extract(
  video: VideoInput,
  channel: ChannelInput = {},
  thumb?: ThumbFeatures | null,
  now: Date = new Date(),
): FeatureRow {
  const published = parseTime(video.publishedAt);
  const ageDays = published
    ? Math.max(0, (now.getTime() - published.getTime()) / 86_400_000)
    : 0;
  const seconds = durationSeconds(video.duration);

  const row: FeatureRow = {
    ...titleFeatures(video.title ?? ''),
    ...descriptionFeatures(video.description ?? ''),
    ...tagFeatures(video.tags),
  };

  row.duration_seconds = seconds;
  row.duration_log = Math.log1p(seconds);
  row.is_shorts = seconds > 0 && seconds <= SHORTS_MAX_SECONDS ? 1 : 0;
  row.is_hd = video.definition === 'hd' ? 1 : 0;
  row.has_captions = video.caption ? 1 : 0;

  const wall = wallClock(video.publishedAt);
  if (wall) {
    // Wall-clock fields as written — see `wallClock`. Matches Python's
    // `published.hour` / `published.weekday()` for every offset, not just Z.
    row.publish_hour = wall.hour;
    row.publish_dow = wall.dow;
    row.publish_weekend = wall.dow >= 5 ? 1 : 0;
  } else {
    row.publish_hour = 0;
    row.publish_dow = 0;
    row.publish_weekend = 0;
  }

  row.age_days_log = Math.log1p(ageDays);
  row.channel_subs_log = Math.log1p(Math.max(0, channel.subscribers ?? 0));
  row.channel_videos_log = Math.log1p(Math.max(0, channel.videoCount ?? 0));
  const channelStarted = parseTime(channel.publishedAt);
  row.channel_age_days_log = Math.log1p(
    channelStarted ? Math.max(0, (now.getTime() - channelStarted.getTime()) / 86_400_000) : 0,
  );
  row.made_for_kids = video.madeForKids ? 1 : 0;
  row.licensed = video.licensedContent ? 1 : 0;

  // `thumb &&` is not enough: Python's `if thumb:` is false for an EMPTY dict, so
  // `{}` must take the zero-fill branch here too. Getting this wrong would give a
  // thumbnail-less video `has_thumb = 1` and absent (rather than zeroed) pixel
  // features - a row shape the trainer never saw.
  if (thumb && Object.keys(thumb).length > 0) {
    for (const name of THUMB_FEATURE_NAMES) {
      const value = thumb[name];
      // Non-finite is coerced to 0 rather than left absent. `thumbs.py` cannot
      // produce a NaN, so this never diverges from Python in practice - but a NaN
      // reaching the tree walker would make every `<=` false and silently route
      // right at every node, which is far worse than a wrong-but-finite feature.
      if (value !== undefined) row[name] = Number.isFinite(value) ? value : 0;
    }
    row.has_thumb = 1;
  } else {
    // Explicit zeros, not absent keys. `toVector` would substitute 0 either way,
    // but the recommender reads the row by name and must see the same thing
    // `features.py` wrote.
    for (const name of THUMB_FEATURE_NAMES) row[name] = 0;
    row.has_thumb = 0;
  }

  return row;
}

/**
 * Build the positional vector the scorer needs.
 *
 * Order comes from the model artefact — never from `Object.keys(row)`, which
 * would silently reorder columns the first time a feature was added.
 */
export function toVector(row: FeatureRow, featureNames: readonly string[]): number[] {
  const vector = new Array<number>(featureNames.length);
  for (let i = 0; i < featureNames.length; i++) {
    const value = row[featureNames[i]];
    vector[i] = Number.isFinite(value) ? value : 0;
  }
  return vector;
}
