/**
 * Feature extraction for the Publish score model — the TypeScript mirror of
 * `ml/publishml/features.py`.
 *
 * THIS FILE AND THE PYTHON ONE MUST AGREE EXACTLY.
 * The model is a positional vector of 64 numbers. If this extractor computes
 * `title_len` differently from the one that produced the training data, every
 * score is wrong in a way that no test of *this* file alone would catch. So:
 *
 *   - the column order comes from the model artefact, never from this file
 *   - `src/lib/ml/features.test.ts` runs both extractors over shared fixtures
 *     exported by `python -m publishml.export` and asserts equality
 *   - the awkward-looking helpers below (`codePoints`, `splitLines`) exist
 *     precisely because the obvious JavaScript is *not* what Python does
 *
 * The three places JavaScript silently disagrees with Python, all handled:
 *   1. `len(s)` counts code points; `s.length` counts UTF-16 units. An emoji is
 *      1 in Python and 2 in JS. → `codePoints()`.
 *   2. `str.splitlines()` returns `[]` for the empty string and drops a trailing
 *      terminator; `split('\n')` returns `['']` and keeps it. → `splitLines()`.
 *   3. `datetime.weekday()` is Monday=0; `Date.getUTCDay()` is Sunday=0.
 *
 * Thumbnail features are NOT computed here. They need pixel access and are
 * produced by `ml/publishml/thumbs.py`; the caller passes them in when it has
 * them. When it does not, they are left absent and `has_thumb` is 0 — the same
 * thing the trainer saw for videos whose thumbnail never downloaded, so the model
 * already knows how to treat that row.
 */

/** The metadata a score needs. Mirrors one row of `raw/videos.jsonl`. */
export type VideoInput = {
  title?: string;
  description?: string;
  tags?: string[];
  /** ISO-8601, e.g. `PT4M13S`. */
  duration?: string | null;
  /** ISO timestamp. Omit for an unpublished draft — see `now` in `extract`. */
  publishedAt?: string | null;
  definition?: string | null;
  caption?: boolean;
  madeForKids?: boolean;
  licensedContent?: boolean;
};

export type ChannelInput = {
  subscribers?: number;
  videoCount?: number;
  /** ISO timestamp of channel creation. */
  publishedAt?: string | null;
};

/** Output of `ml/publishml/thumbs.py` for one image, keys prefixed `thumb_`. */
export type ThumbFeatures = Record<string, number>;

export type FeatureRow = Record<string, number>;

/**
 * The 64 columns, in the exact order `features.feature_names()` returns them.
 *
 * Duplicated here on purpose. The scorer already takes its column order from the
 * model artefact, so this list is not used to build vectors - it is used to CHECK
 * the artefact at load time (`validate` in `gbdt.ts`). Without an independent copy
 * there is nothing to check against, and an artefact trained on a different
 * feature set would load happily and score every video against shifted columns.
 *
 * Generated by `python -m publishml.parity`-adjacent tooling and asserted equal to
 * the fixture in `parity.test.ts`, so it cannot silently drift from Python.
 */
export const FEATURE_NAMES = [
  'age_days_log',
  'channel_age_days_log',
  'channel_subs_log',
  'channel_videos_log',
  'desc_first_line_len',
  'desc_has_cta',
  'desc_hashtags',
  'desc_len',
  'desc_lines',
  'desc_links',
  'desc_timestamps',
  'duration_log',
  'duration_seconds',
  'has_captions',
  'has_thumb',
  'is_hd',
  'is_shorts',
  'licensed',
  'made_for_kids',
  'publish_dow',
  'publish_hour',
  'publish_weekend',
  'tag_avg_words',
  'tag_chars',
  'tag_count',
  'thumb_aspect',
  'thumb_border_fraction',
  'thumb_brightness',
  'thumb_brightness_std',
  'thumb_center_weight',
  'thumb_colorfulness',
  'thumb_complexity',
  'thumb_contrast',
  'thumb_edge_density',
  'thumb_face_area',
  'thumb_face_count',
  'thumb_red_fraction',
  'thumb_saturation',
  'thumb_skin_fraction',
  'thumb_text_area',
  'thumb_text_blocks',
  'thumb_third_offset',
  'thumb_warm_fraction',
  'title_allcaps_words',
  'title_avg_word_len',
  'title_brackets',
  'title_caps_ratio',
  'title_colon',
  'title_curiosity',
  'title_emoji',
  'title_exclaim',
  'title_has_number',
  'title_howto',
  'title_len',
  'title_list',
  'title_longest_word',
  'title_power_words',
  'title_question',
  'title_second_person',
  'title_starts_number',
  'title_stopword_ratio',
  'title_truncated',
  'title_urgency',
  'title_words',
] as const;

/**
 * Features a creator cannot choose: how old the video is, how many subscribers the
 * channel has, whether a thumbnail exists at all.
 *
 * The recommender holds every one of these byte-identical while testing a
 * counterfactual. Otherwise "lift" would include the effect of changing something
 * the creator has no way to change, and the advice would amount to "have more
 * subscribers" or "publish this 200 days earlier".
 */
export const CONTEXT_FEATURES = [
  'age_days_log',
  'channel_age_days_log',
  'channel_subs_log',
  'channel_videos_log',
  'has_thumb',
  'licensed',
  'made_for_kids',
  'thumb_aspect',
] as const;

/** Everything a creator can actually edit before publishing - the only source of advice. */
export const CONTROLLABLE_FEATURES = [
  'desc_first_line_len',
  'desc_has_cta',
  'desc_hashtags',
  'desc_len',
  'desc_lines',
  'desc_links',
  'desc_timestamps',
  'duration_log',
  'duration_seconds',
  'has_captions',
  'is_hd',
  'is_shorts',
  'publish_dow',
  'publish_hour',
  'publish_weekend',
  'tag_avg_words',
  'tag_chars',
  'tag_count',
  'thumb_border_fraction',
  'thumb_brightness',
  'thumb_brightness_std',
  'thumb_center_weight',
  'thumb_colorfulness',
  'thumb_complexity',
  'thumb_contrast',
  'thumb_edge_density',
  'thumb_face_area',
  'thumb_face_count',
  'thumb_red_fraction',
  'thumb_saturation',
  'thumb_skin_fraction',
  'thumb_text_area',
  'thumb_text_blocks',
  'thumb_third_offset',
  'thumb_warm_fraction',
  'title_allcaps_words',
  'title_avg_word_len',
  'title_brackets',
  'title_caps_ratio',
  'title_colon',
  'title_curiosity',
  'title_emoji',
  'title_exclaim',
  'title_has_number',
  'title_howto',
  'title_len',
  'title_list',
  'title_longest_word',
  'title_power_words',
  'title_question',
  'title_second_person',
  'title_starts_number',
  'title_stopword_ratio',
  'title_truncated',
  'title_urgency',
  'title_words',
] as const;

// --- vocabulary (must stay identical to features.py) ------------------------

const POWER_WORDS = new Set([
  'secret', 'proven', 'ultimate', 'essential', 'surprising', 'shocking',
  'brutal', 'honest', 'insane', 'crazy', 'genius', 'perfect', 'instant',
  'hidden', 'forbidden', 'banned', 'exposed', 'revealed', 'truth', 'myth',
  'mistake', 'mistakes', 'warning', 'danger', 'wrong', 'stop', 'avoid',
  'finally', 'actually', 'really', 'definitive', 'complete', 'free',
]);

const CURIOSITY_MARKERS = new Set([
  'why', 'how', 'what', 'when', 'who', 'which', 'nobody', 'everyone',
  'before', 'after', 'until', 'unless', 'happens', 'happened', 'went',
  'turns', 'learned', 'found', 'discovered', 'reason', 'because',
]);

const URGENCY_WORDS = new Set([
  'now', 'today', 'tonight', '2024', '2025', '2026', 'new', 'just', 'breaking',
  'update', 'latest', 'still', 'already', 'immediately', 'quick', 'fast',
]);

const SECOND_PERSON = new Set(['you', 'your', 'yours', "you're", 'youre', 'yourself']);

const STOPWORDS = new Set([
  'a', 'an', 'the', 'and', 'or', 'but', 'of', 'to', 'in', 'on', 'at', 'for',
  'with', 'is', 'it', 'this', 'that', 'as', 'by', 'from', 'was', 'are', 'be',
]);

const CTA_PHRASES = [
  'subscribe', 'like and', 'comment below', 'let me know', 'follow me',
  'join the', 'sign up', 'free guide', 'check out', 'link below', 'patreon',
];

const LIST_PREFIX = /^\s*(\d{1,3})\s*(?:[.)\-:]|\s)/;
const TOP_N = /^\s*top\s+\d/i;
const HOWTO = /\bhow\s+(to|i|we|he|she|they)\b/i;
/** Same code-point ranges as the Python `EMOJI` class; `u` makes both count code points. */
const EMOJI = /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{1F1E6}-\u{1F1FF}\u{2190}-\u{21FF}]/gu;
const BRACKETS = /[[\](){}|]/g;
const URL = /https?:\/\/\S+/g;
const TIMESTAMP = /^\s*\(?\d{1,2}:\d{2}(?::\d{2})?\)?/gm;
/** `\p{L}\p{N}_`, not `\w`: JS `\w` is ASCII-only, Python's `\w` is not. */
const HASHTAG = /(?:^|\s)#[\p{L}\p{N}_]+/gu;
const ISO_DURATION = /^P(?:(\d+)D)?T?(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/;
const WORD_SPLIT = /[^A-Za-z0-9'’]+/;
/** `\p{N}`, matching Python's Unicode-aware `str.isdigit()` closely enough. */
const ANY_DIGIT = /\p{N}/u;
const LETTER = /\p{L}/gu;
const UPPER_LETTER = /\p{Lu}/u;
const LOWER_LETTER = /\p{Ll}/u;

// --- Python-compatibility helpers -------------------------------------------

/** `len(s)` — code points, not UTF-16 units. */
function codePoints(text: string): number {
  // The string iterator yields code points; `.length` counts UTF-16 units and
  // disagrees with Python on every emoji and every astral-plane character.
  return Array.from(text).length;
}

/**
 * `str.splitlines()`.
 *
 * Differs from `split('\n')` in two ways that both change feature values: the
 * empty string yields no lines at all, and a trailing terminator does not
 * produce an empty final line.
 */
function splitLines(text: string): string[] {
  if (text === '') return [];
  // Every terminator Python's splitlines() recognises, written as escapes so the
  // file stays readable. \r\n must come first, or CRLF would split twice and
  // add a phantom empty line to `desc_lines`.
  const lines = text.split(/\r\n|[\n\r\v\f\x1c\x1d\x1e\x85\u2028\u2029]/);
  if (lines.length > 1 && lines[lines.length - 1] === '') lines.pop();
  return lines;
}

function words(text: string): string[] {
  return text.split(WORD_SPLIT).filter((w) => w.length > 0);
}

function countMatches(text: string, pattern: RegExp): number {
  const matches = text.match(pattern);
  return matches ? matches.length : 0;
}

function countSubstring(text: string, needle: string): number {
  if (!needle) return 0;
  return text.split(needle).length - 1;
}

/** `w.isupper()` — at least one cased character, and none of them lowercase. */
function isAllCaps(word: string): boolean {
  return UPPER_LETTER.test(word) && !LOWER_LETTER.test(word);
}

/** ISO-8601 duration → seconds. Mirrors `_duration_seconds`. */
export function durationSeconds(iso?: string | null): number {
  if (!iso) return 0;
  const m = ISO_DURATION.exec(iso.trim());
  if (!m) return 0;
  const [, d, h, mi, s] = m;
  return (
    (d ? parseInt(d, 10) : 0) * 86400 +
    (h ? parseInt(h, 10) : 0) * 3600 +
    (mi ? parseInt(mi, 10) : 0) * 60 +
    (s ? parseInt(s, 10) : 0)
  );
}

function parseTime(value?: string | null): Date | null {
  if (!value) return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

// --- feature groups ---------------------------------------------------------

export function titleFeatures(rawTitle: string): FeatureRow {
  const title = rawTitle || '';
  const ws = words(title);
  const lower = ws.map((w) => w.toLowerCase());
  const letters = title.match(LETTER) ?? [];
  const uppers = letters.filter((c) => UPPER_LETTER.test(c)).length;
  const len = codePoints(title);
  const totalWordLen = ws.reduce((sum, w) => sum + codePoints(w), 0);

  return {
    title_len: len,
    title_words: ws.length,
    title_caps_ratio: letters.length ? uppers / letters.length : 0,
    title_allcaps_words: ws.filter((w) => codePoints(w) > 2 && isAllCaps(w)).length,
    title_has_number: ANY_DIGIT.test(title) ? 1 : 0,
    title_starts_number: LIST_PREFIX.test(title) ? 1 : 0,
    title_question: title.includes('?') ? 1 : 0,
    title_exclaim: countSubstring(title, '!'),
    title_brackets: countMatches(title, BRACKETS),
    title_emoji: countMatches(title, EMOJI),
    title_colon:
      countSubstring(title, ':') + countSubstring(title, '|') + countSubstring(title, ' - '),
    title_second_person: lower.filter((w) => SECOND_PERSON.has(w)).length,
    title_power_words: lower.filter((w) => POWER_WORDS.has(w)).length,
    title_curiosity: lower.filter((w) => CURIOSITY_MARKERS.has(w)).length,
    title_urgency: lower.filter((w) => URGENCY_WORDS.has(w)).length,
    title_howto: HOWTO.test(title) ? 1 : 0,
    title_list: LIST_PREFIX.test(title) || TOP_N.test(title) ? 1 : 0,
    title_avg_word_len: ws.length ? totalWordLen / ws.length : 0,
    title_longest_word: ws.reduce((max, w) => Math.max(max, codePoints(w)), 0),
    title_stopword_ratio: lower.length
      ? lower.filter((w) => STOPWORDS.has(w)).length / lower.length
      : 0,
    title_truncated: len > 60 ? 1 : 0,
  };
}

export function descriptionFeatures(rawDesc: string): FeatureRow {
  const desc = rawDesc || '';
  const lines = splitLines(desc);
  const first = lines.length ? lines[0] : '';
  const low = desc.toLowerCase();
  return {
    desc_len: codePoints(desc),
    desc_lines: lines.length,
    desc_links: countMatches(desc, URL),
    desc_timestamps: countMatches(desc, TIMESTAMP),
    desc_hashtags: countMatches(desc, HASHTAG),
    desc_first_line_len: codePoints(first),
    desc_has_cta: CTA_PHRASES.some((p) => low.includes(p)) ? 1 : 0,
  };
}

export function tagFeatures(tags?: string[]): FeatureRow {
  const list = tags ?? [];
  const wordCount = list.reduce(
    (sum, t) => sum + t.trim().split(/\s+/).filter(Boolean).length,
    0,
  );
  return {
    tag_count: list.length,
    tag_chars: list.reduce((sum, t) => sum + codePoints(t), 0),
    tag_avg_words: list.length ? wordCount / list.length : 0,
  };
}

/** Seconds at or below this are treated as a Short. Mirrors `config.SHORTS_MAX_SECONDS`. */
export const SHORTS_MAX_SECONDS = 60;

/**
 * Every `thumb_*` column, in the order `ml/publishml/thumbs.py` declares them.
 *
 * Listed explicitly rather than derived from the passed-in object, because both
 * branches below need the full set: the present branch must ignore keys the model
 * does not know, and the absent branch must write a zero for each one.
 */
export const THUMB_FEATURE_NAMES = [
  'thumb_brightness',
  'thumb_brightness_std',
  'thumb_contrast',
  'thumb_saturation',
  'thumb_colorfulness',
  'thumb_warm_fraction',
  'thumb_red_fraction',
  'thumb_edge_density',
  'thumb_text_area',
  'thumb_text_blocks',
  'thumb_face_area',
  'thumb_face_count',
  'thumb_skin_fraction',
  'thumb_center_weight',
  'thumb_third_offset',
  'thumb_complexity',
  'thumb_border_fraction',
  'thumb_aspect',
] as const;

/**
 * The full feature row.
 *
 * `now` is a parameter, not `new Date()`, for two reasons: the parity test needs
 * a fixed clock, and a score that silently changes because a day passed is a
 * score nobody can debug.
 */
export function extract(
  video: VideoInput,
  channel: ChannelInput = {},
  thumb?: ThumbFeatures | null,
  now: Date = new Date(),
): FeatureRow {
  const published = parseTime(video.publishedAt);
  const ageDays = published
    ? Math.max(0, (now.getTime() - published.getTime()) / 86_400_000)
    : 0;
  const seconds = durationSeconds(video.duration);

  const row: FeatureRow = {
    ...titleFeatures(video.title ?? ''),
    ...descriptionFeatures(video.description ?? ''),
    ...tagFeatures(video.tags),
  };

  row.duration_seconds = seconds;
  row.duration_log = Math.log1p(seconds);
  row.is_shorts = seconds > 0 && seconds <= SHORTS_MAX_SECONDS ? 1 : 0;
  row.is_hd = video.definition === 'hd' ? 1 : 0;
  row.has_captions = video.caption ? 1 : 0;

  if (published) {
    row.publish_hour = published.getUTCHours();
    // Python's `weekday()` is Monday=0; JS `getUTCDay()` is Sunday=0.
    row.publish_dow = (published.getUTCDay() + 6) % 7;
    row.publish_weekend = row.publish_dow >= 5 ? 1 : 0;
  } else {
    row.publish_hour = 0;
    row.publish_dow = 0;
    row.publish_weekend = 0;
  }

  row.age_days_log = Math.log1p(ageDays);
  row.channel_subs_log = Math.log1p(Math.max(0, channel.subscribers ?? 0));
  row.channel_videos_log = Math.log1p(Math.max(0, channel.videoCount ?? 0));
  const channelStarted = parseTime(channel.publishedAt);
  row.channel_age_days_log = Math.log1p(
    channelStarted ? Math.max(0, (now.getTime() - channelStarted.getTime()) / 86_400_000) : 0,
  );
  row.made_for_kids = video.madeForKids ? 1 : 0;
  row.licensed = video.licensedContent ? 1 : 0;

  // `thumb &&` is not enough: Python's `if thumb:` is false for an EMPTY dict, so
  // `{}` must take the zero-fill branch here too. Getting this wrong would give a
  // thumbnail-less video `has_thumb = 1` and absent (rather than zeroed) pixel
  // features - a row shape the trainer never saw.
  if (thumb && Object.keys(thumb).length > 0) {
    for (const name of THUMB_FEATURE_NAMES) {
      const value = thumb[name];
      // Non-finite is coerced to 0 rather than left absent. `thumbs.py` cannot
      // produce a NaN, so this never diverges from Python in practice - but a NaN
      // reaching the tree walker would make every `<=` false and silently route
      // right at every node, which is far worse than a wrong-but-finite feature.
      if (value !== undefined) row[name] = Number.isFinite(value) ? value : 0;
    }
    row.has_thumb = 1;
  } else {
    // Explicit zeros, not absent keys. `toVector` would substitute 0 either way,
    // but the recommender reads the row by name and must see the same thing
    // `features.py` wrote.
    for (const name of THUMB_FEATURE_NAMES) row[name] = 0;
    row.has_thumb = 0;
  }

  return row;
}

/**
 * Build the positional vector the scorer needs.
 *
 * Order comes from the model artefact — never from `Object.keys(row)`, which
 * would silently reorder columns the first time a feature was added.
 */
export function toVector(row: FeatureRow, featureNames: readonly string[]): number[] {
  const vector = new Array<number>(featureNames.length);
  for (let i = 0; i < featureNames.length; i++) {
    const value = row[featureNames[i]];
    vector[i] = Number.isFinite(value) ? value : 0;
  }
  return vector;
}
